options:
  formatter: stylish
rules:
  # Extends
  extends-before-mixins: 1
  extends-before-declarations: 1
  placeholder-in-extend: 0

  # Mixins
  mixins-before-declarations: 1

  # Line Spacing
  one-declaration-per-line: 1
  empty-line-between-blocks: 0
  single-line-per-selector: 1

  # Disallows
  no-color-keywords: 1
  no-color-literals: 1
  no-css-comments: 0
  no-debug: 1
  no-duplicate-properties:
  - 1
  -
    exclude:
      - vertical-align
  no-empty-rulesets: 1
  no-extends: 0
  no-ids: 0
  no-important: 0
  no-invalid-hex: 1
  no-mergeable-selectors: 1
  no-misspelled-properties:
    - 1
    -
      'extra-properties':
        - 'font-smooth'
  no-qualifying-elements:
    - 1
    -
      allow-element-with-attribute: true
      allow-element-with-class: true
      allow-element-with-id: true
  no-trailing-zero: 1
  no-transition-all: 1
  no-url-protocols: 0
  no-url-domains: 0
  no-vendor-prefixes: 0
  no-warn: 1

  # Nesting
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0

  # Name Formats
  function-name-format: 1
  mixin-name-format: 1
  placeholder-name-format: 1
  class-name-format: 0
  variable-name-format:
    - 1
    -
      allow-leading-underscore: false

  # Style Guide
  border-zero: 1
  brace-style: 1
  clean-import-paths: 0
  empty-args: 1
  hex-length: 1
  hex-notation: 1
  indentation: 1
  leading-zero: 0
  nesting-depth: 0
  property-sort-order:
    - 1
    - order: concentric
  quotes: 1
  shorthand-values: 1
  url-quotes: 1
  variable-for-property: 1
  zero-unit: 1

  # Inner Spacing
  space-after-comma: 1
  space-before-colon: 1
  space-after-colon: 1
  space-before-brace: 1
  space-before-bang: 1
  space-after-bang: 1
  space-between-parens: 1

  # Final Items
  trailing-semicolon: 1
  final-newline: 1